name:                tensor-hmatrix
version:             0.1.0.0
github:              "mstksg/tensor-hmatrix"
license:             BSD3
author:              "Justin Le"
maintainer:          "justin@jle.im"
copyright:           "(c) Justin Le 2018"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mstksg/tensor-hmatrix#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall

library:
  source-dirs: src
  reexported-modules: Tensor.HMatrix as Tensor
  dependencies:
  - hmatrix
  - singletons
  - type-combinators
  - finite-typelits
  - vector
  - ghc-typelits-knownnat
  - vector-sized >= 1.0.2
